### ISSUE TITLE
Docs suggestion: Clarify use with release tags

### ISSUE THREAD

**Issue by udf2457** [actions/attest#50]
Thank you for your work on this.

It is not clear how to use the input to define a tagged release.

For example, assume my github action fires on commit of a new tag to create a new release with assets named inline with the tag number e.g. `foo_$tagNumber_darwin_amd64.tar.gz`.

Its not quite clear, at least to me, how to integrate `attest` with this sort of dynamic naming.

**Comment by bdehamer** [comment]
When specifying the value for the `subject-path` input parameter you can use any sort of GitHub Action-supported expression. If the name of the tag is present in an environment variable you could do something like:

```yaml
- uses: actions/attest-build-provenance@v1
  with:
    subject-path: foo_${{ env.tagNumber }}_darwin_amd64.tar.gz
```

or maybe you have the entire name of the asset set as the output value of a previous step:

```yaml
- uses: actions/attest-build-provenance@v1
  with:
    subject-path: ${{ steps.build.outputs.asset_name }}
```
